#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J mbirjax_cpu
#SBATCH --mail-user=hasitha@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -A als
#SBATCH -t 00:30:0

module load python
conda activate mbirjax

#run the application: 
srun -n 1 -c 256  -l -u python /global/u1/h/hasitha/EMSL-XCT/backend/fdk_script.py
