#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C gpu&hbm80g 
#SBATCH -G 1
#SBATCH -q debug
#SBATCH -J mbirjax_debug
#SBATCH --mail-user=hasitha@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -A als
#SBATCH -t 00:30:00


module load python
conda activate mbirjax

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -n 1 -c 128 -l -u python /global/u1/h/hasitha/EMSL-XCT/backend/mbir_script.py