#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -G 1
#SBATCH -q regular
#SBATCH -J mbirjax1
#SBATCH --mail-user=hasitha@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -A als
#SBATCH -t 10:0:0


module load python
conda activate mbirjax

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -l -u python /global/u1/h/hasitha/EMSL-XCT/backend/mbir_script.py